name: Frontend CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env
        run: |
          echo "VITE_API_URL=https://justus-server.onrender.com/api" >> .env
          echo "VITE_SOCKET_URL=https://justus-server.onrender.com" >> .env

      - name: Build
        run: npm run build